/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterDto"];
                    "text/json": components["schemas"]["RegisterDto"];
                    "application/*+json": components["schemas"]["RegisterDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserResponseDto"];
                        "application/json": components["schemas"]["UserResponseDto"];
                        "text/json": components["schemas"]["UserResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginDto"];
                    "text/json": components["schemas"]["LoginDto"];
                    "application/*+json": components["schemas"]["LoginDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intakes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IntakeResponseDto"];
                        "application/json": components["schemas"]["IntakeResponseDto"];
                        "text/json": components["schemas"]["IntakeResponseDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IntakeDto"];
                    "text/json": components["schemas"]["IntakeDto"];
                    "application/*+json": components["schemas"]["IntakeDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IntakeResponseDto"];
                        "application/json": components["schemas"]["IntakeResponseDto"];
                        "text/json": components["schemas"]["IntakeResponseDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IntakeResponseDto"][];
                        "application/json": components["schemas"]["IntakeResponseDto"][];
                        "text/json": components["schemas"]["IntakeResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IntakeDto"];
                    "text/json": components["schemas"]["IntakeDto"];
                    "application/*+json": components["schemas"]["IntakeDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IntakeResponseDto"];
                        "application/json": components["schemas"]["IntakeResponseDto"];
                        "text/json": components["schemas"]["IntakeResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MedicationDto"];
                        "application/json": components["schemas"]["MedicationDto"];
                        "text/json": components["schemas"]["MedicationDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MedicationDto"];
                    "text/json": components["schemas"]["MedicationDto"];
                    "application/*+json": components["schemas"]["MedicationDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MedicationDto"];
                        "application/json": components["schemas"]["MedicationDto"];
                        "text/json": components["schemas"]["MedicationDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MedicationDto"][];
                        "application/json": components["schemas"]["MedicationDto"][];
                        "text/json": components["schemas"]["MedicationDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MedicationDto"];
                    "text/json": components["schemas"]["MedicationDto"];
                    "application/*+json": components["schemas"]["MedicationDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MedicationDto"];
                        "application/json": components["schemas"]["MedicationDto"];
                        "text/json": components["schemas"]["MedicationDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prescriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PrescriptionResponseDto"];
                        "application/json": components["schemas"]["PrescriptionResponseDto"];
                        "text/json": components["schemas"]["PrescriptionResponseDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PrescriptionDto"];
                    "text/json": components["schemas"]["PrescriptionDto"];
                    "application/*+json": components["schemas"]["PrescriptionDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PrescriptionResponseDto"];
                        "application/json": components["schemas"]["PrescriptionResponseDto"];
                        "text/json": components["schemas"]["PrescriptionResponseDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prescriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PrescriptionResponseDto"][];
                        "application/json": components["schemas"]["PrescriptionResponseDto"][];
                        "text/json": components["schemas"]["PrescriptionResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PrescriptionDto"];
                    "text/json": components["schemas"]["PrescriptionDto"];
                    "application/*+json": components["schemas"]["PrescriptionDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PrescriptionResponseDto"];
                        "application/json": components["schemas"]["PrescriptionResponseDto"];
                        "text/json": components["schemas"]["PrescriptionResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserResponseDto"];
                        "application/json": components["schemas"]["UserResponseDto"];
                        "text/json": components["schemas"]["UserResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserResponseDto"][];
                        "application/json": components["schemas"]["UserResponseDto"][];
                        "text/json": components["schemas"]["UserResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserRole"];
                    "text/json": components["schemas"]["UserRole"];
                    "application/*+json": components["schemas"]["UserRole"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserResponseDto"];
                        "application/json": components["schemas"]["UserResponseDto"];
                        "text/json": components["schemas"]["UserResponseDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/{id}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Frequency: "OnceADay" | "TwiceADay" | "ThriceADay" | "EveryOtherDay" | "Weekly";
        IntakeDto: {
            /** Format: date-time */
            scheduledAt: string;
            /** Format: date-time */
            takenAt?: string | null;
            readonly isTaken?: boolean;
            comment?: string | null;
            /** Format: int32 */
            prescriptionId?: number;
        };
        IntakeResponseDto: {
            /** Format: int32 */
            id?: number;
            /** Format: date-time */
            scheduledAt?: string;
            /** Format: date-time */
            takenAt?: string | null;
            readonly isTaken?: boolean;
            comment?: string | null;
            medicationName?: string | null;
            doctorName?: string | null;
        };
        LoginDto: {
            userName?: string | null;
            password?: string | null;
        };
        MedicationDto: {
            name: string;
            description?: string | null;
            dosageForm: string;
        };
        PrescriptionDto: {
            dosage: string;
            frequency?: components["schemas"]["Frequency"];
            /** Format: date-time */
            startDate: string;
            /** Format: int32 */
            period?: number;
            isFlexible?: boolean;
            comment?: string | null;
            /** Format: int32 */
            patientId?: number;
            /** Format: int32 */
            medicationId?: number;
        };
        PrescriptionResponseDto: {
            /** Format: int32 */
            id?: number;
            dosage?: string | null;
            frequency?: components["schemas"]["Frequency"];
            /** Format: date-time */
            startDate?: string;
            /** Format: int32 */
            period?: number;
            isFlexible?: boolean;
            comment?: string | null;
            patientName?: string | null;
            medicationName?: string | null;
            doctorName?: string | null;
        };
        RegisterDto: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        UserResponseDto: {
            /** Format: int32 */
            id?: number;
            userName?: string | null;
            email?: string | null;
            role?: components["schemas"]["UserRole"];
        };
        /** @enum {string} */
        UserRole: "Administrator" | "Doctor" | "Patient";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
